name = "BluePrintDemo"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BluePrintDemo"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0"

[[lean_lib]]
name = "BluePrintDemo"
