name = "BluePrintDemo"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BluePrintDemo"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.26.0"

[[lean_lib]]
name = "BluePrintDemo"
